---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dograh-asterisk
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dograh-asterisk-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ASTERISK_ARI_PASSWORD: "{{ .ASTERISK_ARI_PASSWORD }}"
        UNIFI_TALK_SIP_SERVER: "{{ .UNIFI_TALK_SIP_SERVER }}"
        UNIFI_TALK_SIP_USERNAME: "{{ .UNIFI_TALK_SIP_USERNAME }}"
        UNIFI_TALK_SIP_PASSWORD: "{{ .UNIFI_TALK_SIP_PASSWORD }}"
  dataFrom:
    - extract:
        key: dograh
