---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: configarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
  dataFrom:
    - extract:
        key: lidarr
