apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecret.yaml

helmCharts:
- name: democratic-csi
  repo: https://democratic-csi.github.io/charts/
  version: 0.15.1
  releaseName: zfs-iscsi
  namespace: kube-system
  valuesInline:
    csiDriver:
      name: "zfs-iscsi.democratic-csi.bastion"
    storageClasses:
    - name: zfs-nvme
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
        detachedVolumesFromSnapshots: "false"
      mountOptions: []
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    volumeSnapshotClasses:
    - name: zfs-nvme-snapshot
      deletionPolicy: Delete
      parameters:
        detachedSnapshots: "true"
    driver:
      existingConfigSecret: zfs-iscsi-purplebox
      config:
        driver: zfs-generic-iscsi
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /etc/iscsi
        iscsiDirHostPathType: ""
