---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dograh-db-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dograh-db-superuser
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: postgres
        password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: dograh
