---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gamarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gamarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH_USERNAME: "{{ .AUTH_USERNAME }}"
        AUTH_PASSWORD: "{{ .AUTH_PASSWORD }}"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        SABNZBD_API_KEY: "{{ .SABNZBD_API_KEY }}"
  dataFrom:
    - extract:
        key: gamarr
    - extract:
        key: prowlarr
    - extract:
        key: sabnzbd
