---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metamcp
  labels:
    app.kubernetes.io/name: metamcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-nvme
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: metamcp-rdst
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-vault
  labels:
    app.kubernetes.io/name: metamcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zfs-nvme
  resources:
    requests:
      storage: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: metamcp-rdst
  labels:
    app.kubernetes.io/name: metamcp
spec:
  trigger:
    manual: restore-zfs-snapshot
  restic:
    repository: metamcp-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: zfs-nvme
    cacheStorageClassName: zfs-nvme
    volumeSnapshotClassName: zfs-nvme-snapshot
    capacity: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: metamcp
  labels:
    app.kubernetes.io/name: metamcp
spec:
  sourcePVC: metamcp
  trigger:
    schedule: "0 2 * * *"
  restic:
    pruneIntervalDays: 7
    repository: metamcp-restic-secret
    retain:
      daily: 7
      weekly: 4
    copyMethod: Snapshot
    storageClassName: zfs-nvme
    volumeSnapshotClassName: zfs-nvme-snapshot
