---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hermes
  annotations:
    link.argocd.argoproj.io/external-link: https://hermes.tailnet-4d89.ts.net
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - hermes
  rules:
    - host: hermes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hermes
                port:
                  number: 9119
