apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kagent
spec:
  ingressClassName: tailscale
  rules:
    - host: kagent
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kagent-ui
                port:
                  number: 8080
  tls:
    - hosts:
        - kagent
