apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml
  - persistence.yaml
  - ingress.yaml

helmCharts:
  - name: kagent-crds
    repo: oci://ghcr.io/kagent-dev/kagent/helm
    version: 0.9.9
    releaseName: kagent-crds
    namespace: kagent
  - name: kagent
    repo: oci://ghcr.io/kagent-dev/kagent/helm
    version: 0.9.9
    releaseName: kagent
    namespace: kagent
    valuesFile: values.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: kagent-postgresql
    patch: |-
      - op: add
        path: /spec/dataSourceRef
        value:
          apiGroup: volsync.backube
          kind: ReplicationDestination
          name: kagent-postgresql-rdst
