---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: kagent-postgresql-rdst
spec:
  trigger:
    manual: restore-zfs-snapshot
  restic:
    repository: kagent-postgresql-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: zfs-nvme
    cacheStorageClassName: zfs-nvme
    volumeSnapshotClassName: zfs-nvme-snapshot
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    capacity: 500Mi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: kagent-postgresql-rsrc
spec:
  sourcePVC: kagent-postgresql
  trigger:
    schedule: "15 */8 * * *"
  restic:
    pruneIntervalDays: 7
    repository: kagent-postgresql-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: zfs-nvme
    cacheStorageClassName: zfs-nvme
    volumeSnapshotClassName: zfs-nvme-snapshot
    moverSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    retain:
      hourly: 24
      daily: 7
      weekly: 5
