apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-eso-bastion
  target:
    name: proxmox-csi-plugin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          clusters:
            - url: "{{ .PROXMOX_CSI_URL }}"
              insecure: true
              token_id: "{{ .PROXMOX_CSI_TOKEN_ID }}"
              token_secret: "{{ .PROXMOX_CSI_TOKEN_SECRET }}"
              region: "{{ .PROXMOX_CSI_REGION }}"
  data:
    - secretKey: PROXMOX_CSI_URL
      remoteRef:
        key: PROXMOX_CSI_URL
    - secretKey: PROXMOX_CSI_TOKEN_ID
      remoteRef:
        key: PROXMOX_CSI_TOKEN_ID
    - secretKey: PROXMOX_CSI_TOKEN_SECRET
      remoteRef:
        key: PROXMOX_CSI_TOKEN_SECRET
    - secretKey: PROXMOX_CSI_REGION
      remoteRef:
        key: PROXMOX_CSI_REGION
