---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dograh-minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dograh-minio-env-configuration
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_ROOT_USER="{{ .MINIO_ROOT_USER }}"
          export MINIO_ROOT_PASSWORD="{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: dograh
