apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dograh
resources:
  - externalsecret.yaml
helmCharts:
  - name: tenant
    repo: https://operator.min.io/
    version: 7.1.1
    releaseName: dograh-minio
    valuesInline:
      tenant:
        name: dograh-minio
        image:
          repository: quay.io/minio/minio
          tag: RELEASE.2025-04-08T15-41-24Z
          pullPolicy: IfNotPresent
        configSecret:
          name: dograh-minio-env-configuration
          existingSecret: true
        env:
          - name: MINIO_API_CORS_ALLOW_ORIGIN
            value: "*"
        pools:
          - name: pool-0
            servers: 1
            volumesPerServer: 1
            size: 10Gi
            storageClassName: zfs-nvme
            storageLabels:
              app.kubernetes.io/name: dograh
              app.kubernetes.io/component: minio
        mountPath: /export
        subPath: /data
        certificate:
          requestAutoCert: false
        features:
          bucketDNS: false
          enableSFTP: false
        buckets:
          - name: voice-audio
            region: us-east-1
        podManagementPolicy: Parallel
        prometheusOperator: false
      ingress:
        api:
          enabled: true
          ingressClassName: tailscale
          host: dograh-minio
          tls:
            - hosts:
                - dograh-minio
        console:
          enabled: false
