VERSION 0.6

tailscale-latest-version:
  FROM alpine
  RUN apk add curl jq
  RUN tarball="$(curl 'https://pkgs.tailscale.com/stable/?mode=json' | jq -r .Tarballs.amd64)" && \
      version="$(echo ${tarball} | cut -d_ -f2)" && \
      echo $version > /tailscale.version
  SAVE ARTIFACT /tailscale.version

tailscale-download:
  FROM alpine
  RUN apk add curl jq tree

  RUN tarball="$(curl 'https://pkgs.tailscale.com/stable/?mode=json' | jq -r .Tarballs.amd64)" && \
      version="$(echo ${tarball} | cut -d_ -f2)" && \
      curl "https://pkgs.tailscale.com/stable/${tarball}" -o tailscale.tgz && \
      mkdir -p \
          /tailscale/usr/bin \
          /tailscale/usr/sbin \
          /tailscale/usr/lib/systemd/system \
          /tailscale/usr/lib/extension-release.d && \
      tree /tailscale && \
      tar xzf tailscale.tgz && \
      echo ${version} > /tailscale/version && \
      cp -vrf "tailscale_${version}_amd64"/tailscale /tailscale/usr/bin/tailscale && \
      cp -vrf "tailscale_${version}_amd64"/tailscaled /tailscale/usr/sbin/tailscaled && \
      cp -vrf "tailscale_${version}_amd64"/systemd/tailscaled.service /tailscale/usr/lib/systemd/system/tailscaled.service && \
      sed -i 's/--port.*//g' /tailscale/usr/lib/systemd/system/tailscaled.service
  SAVE ARTIFACT /tailscale/*

version:
  FROM alpine
  COPY +tailscale-latest-version/tailscale.version /extension.version
  ARG VERSION=$(cat /extension.version)
  ENV VERSION=$VERSION
  RUN echo $VERSION
  SAVE ARTIFACT /extension.version

extension:
  FROM ubuntu:jammy
  
  ARG KAIROS_VERSION
  ENV KAIROS_VERSION=$KAIROS_VERSION
  COPY +tailscale-latest-version/tailscale.version /tailscale.version
  ARG TAILSCALE_VERSION=$(cat /tailscale.version)
  RUN apt update -yqq && apt install -yqq curl tree
  RUN mkdir -p --mode=0755 /usr/share/keyrings && \
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null && \
      curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | tee /etc/apt/sources.list.d/tailscale.list && \
      apt-get update -yqq && apt-get install -yqq tailscale
  RUN uname -m
  RUN sed -i 's/--port.*//g' /usr/lib/systemd/system/tailscaled.service

  RUN mkdir -p /usr/lib/extension-release.d && \
      echo ID=kairos > /usr/lib/extension-release.d/extension-release.tailscale && \
      echo VERSION_ID=$KAIROS_VERSION >> /usr/lib/extension-release.d/extension-release.tailscale && \
      echo EXT_VERSION=$(cat /tailscale.version) >> /usr/lib/extension-release.d/extension-release.tailscale
  
  RUN mkdir -p /tailscale/usr/lib/systemd/system \
        /tailscale/usr/lib/extension-release.d \
        /tailscale/usr/sbin \
        /tailscale/usr/bin && \
      cp /usr/bin/tailscale /tailscale/usr/bin/tailscale && \
      cp /usr/sbin/tailscaled /tailscale/usr/sbin/tailscaled && \
      cp /usr/lib/extension-release.d/extension-release.tailscale /tailscale/usr/lib/extension-release.d/extension-release.tailscale && \
      cp /usr/lib/systemd/system/tailscaled.service /tailscale/usr/lib/systemd/system/tailscaled.service

  SAVE ARTIFACT /tailscale/ extension

extension-image:
  FROM scratch
  ARG KAIROS_VERSION
  ARG IMG
  COPY (+extension/extension --KAIROS_VERSION=$KAIROS_VERSION) /
  SAVE IMAGE $IMG