---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

controllers:
  lidarr:
    initContainers:
      init-db:
        image:
          repository: ghcr.io/home-operations/postgres-init
          tag: 18
        envFrom: &envFrom
          - secretRef:
              name: lidarr-secret
    containers:
      app: &appcontainer
        image:
          repository: ghcr.io/home-operations/lidarr
          tag: rolling@sha256:9df1e14c8e09745f23a36c0cc6adcf69665b379aae60e5a7cb9bda27961ef4e7
        env:
          LIDARR__APP__INSTANCENAME: Lidarr
          LIDARR__APP__THEME: dark
          LIDARR__AUTH__METHOD: External
          LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
          LIDARR__LOG__LEVEL: info
          LIDARR__SERVER__PORT: &port 8686
          LIDARR__UPDATE__BRANCH: develop
          TZ: America/Chicago
        envFrom: *envFrom
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
persistence:
  config:
    existingClaim: &app lidarr
  logs:
    type: emptyDir
    globalMounts:
      - path: /config/logs
  media:
    type: nfs
    server: truenas-purplebox.private.home
    path: /mnt/purple/general/media
  tmp:
    type: emptyDir
ingress:
  app:
    enabled: true
    className: tailscale
    hosts:
      - host: *app
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *app
service:
  app:
    controller: *app
    ports:
      http:
        port: *port
