apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dograh
helmCharts:
  - name: valkey
    repo: https://valkey.io/valkey-helm/
    version: 0.9.4
    releaseName: dograh-valkey
    valuesInline:
      fullnameOverride: dograh-valkey
      auth:
        enabled: true
        existingSecret: dograh-secret
        existingSecretPasswordKey: VALKEY_PASSWORD
        usersExistingSecret: dograh-secret
        aclUsers:
          default:
            permissions: "~* &* +@all"
            passwordKey: VALKEY_PASSWORD
      dataStorage:
        enabled: false
      metrics:
        enabled: false
